version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - MEDIAPIPE_DETECTION_CONFIDENCE=0.7
      - MEDIAPIPE_TRACKING_CONFIDENCE=0.7
      - DEBUG=1
      - DISPLAY=:99
      - QT_X11_NO_MITSHM=1
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix  # For X11 forwarding
    devices:
      - /dev/video0:/dev/video0  # For webcam access
    restart: unless-stopped
